name: hffp
spec-version: 0.36.0

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/OlaoluwaM/haskell-from-first-principles-exercises#readme>

dependencies:
  - base

default-extensions:
  - ImportQualifiedPost
  - LambdaCase
  - TypeApplications

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  # - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
    - random
    - time
    - PyF
    - containers
    - hspec
    - QuickCheck
    - checkers

executables:
  hffp:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hffp

tests:
  hffp-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hffp
      - hspec
      - QuickCheck
      - containers
      - checkers
      - hspec-checkers
